services:
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306

    environment:
      - MYSQL_DATABASE=auction
      - MYSQL_ROOT_PASSWORD=${PASSWORD}

    volumes:
      - ../mysqldatauction:/var/lib/mysql

  django:
    build: .
    command: ./wait-for-it.sh mysql:3306 -- ./entrypoint.sh

    ports:
      - "8000:8000"

    volumes:
      - .:/app

    depends_on:
      - mysql
      - redis


    restart: on-failure
  
  redis:
    image: redis

    ports:
      - '6379:6379'

    restart: on-failure

  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - "80:80"  
  #     # - "443:443" # Map port 443 of the container to port 443 on the host
  #   volumes:
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  #     - ./staticfiles:/app/static
  #     - ./media:/app/media
  #   depends_on:
  #     - django
  #   restart: always

