# Generated by Django 5.0.7 on 2024-07-21 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='ending_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_auctions', to='auction_api.profile'),
        ),
    ]
