# Generated by Django 5.0.7 on 2024-07-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_api', '0002_auction_ending_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='finishing_bid',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='starting_bid',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
